name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_lint:
    name: Build and lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install packages
        run: npm install

      - name: Build package
        run: npm run build

      - name: Check formatting
        run: npm run prettier

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16, 18, latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run clean install
        run: npm ci

      - name: Set up Erland Server
        run: docker run -d -p 8080:8080 meppu/erland:main

      # Container is not ready for connection
      # sometimes, so we sleep a bit to make sure.
      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Run tests
        run: npm test
