name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Generate changelog
        continue-on-error: true
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Clean install packages
        run: npm ci

      - name: Publish to NPM
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org'

      - name: Publish to GitHub Packages
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
          NPM_CONFIG_REGISTRY: https://npm.pkg.github.com
          NPM_CONFIG_SCOPE: '@erland-beam'
