name: Test workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test for ${{ matrix.node-version }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Setup Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run clean install
        run: npm ci

      - name: Check format
        run: npm run prettier

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
