name: Test workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        node_version: [16, 18, latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Setup Node.js ${{ matrix.node_version }}
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run clean install
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Set up Erland Server
        run: docker run -d -p 8080:8080 meppu/erland:main

      # Container is not ready for connection
      # sometimes, so we sleep a bit to make sure.
      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Run tests
        run: npm test
