name: Test workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        node_version: [16, 18, latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Setup Node.js ${{ matrix.node_version }}
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run clean install
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Set up Erland Server
        run: docker run -d -p 8080:8080 meppu/erland:main

      - name: Run tests
        timeout-minutes: 1
        run: npm test
